project:
  type: book

book:
  title: "Using Github for Scientific Collaboration"
  author:
  - name: Xiaoxiao Li
    orcid: 0000-0002-4029-2162
  - name: Tanya Strydom
    orcid: 0000-0001-6067-1349
  date: now
  favicon: assets/logo.png
  sidebar: 
    logo: assets/logo.png
    search: true
  repo-url: https://github.com/BecksLab/tutorial_github

  chapters:
    - index.qmd
    - part: "Gitting Started"
      chapters: 
        - basics.qmd
        - branches.qmd
        - collaborating.qmd
    - part: "Next steps"
      chapters:
        - maximising.qmd
        - project_management.qmd
        - content.qmd


bibliography: references.bib

format:
  html:
    theme: [minty, mystyles.scss]
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.0rem

execute:
  freeze: auto



