project:
  type: book

book:
  title: "Using Github for Scientific Collaboration"
  author:
  - name: Xiaoxiao Li
    orcid: 0000-0002-4029-2162
  - name: Tanya Strydom
    orcid: 0000-0001-6067-1349
  date: now
  favicon: assets/logo.png
  sidebar: 
    background: "#F5F5F5"
    logo: assets/logo.png
    search: true
  repo-url: https://github.com/BecksLab/tutorial_github

  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd


bibliography: references.bib

format:
  html:
    theme: [minty, mystyles.scss]
    toc: true

execute:
  freeze: auto



